---
name: Linting
description: Runs pre-commit over the repo

inputs:
  pre-commit-config:
    description: The pre-commit config file of the current repo
    required: true

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Cache pre-commit
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.cache/pre-commit
        key: cache-${{ hashFiles(inputs.pre-commit-config) }}

    - name: Set up python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
      with:
        python-version: 3.x

    - name: Install pre-commit
      shell: bash
      run: python -m pip install pre-commit

    - name: Run pre-commit
      shell: bash
      run: pre-commit run --all-files --color always --verbose

    # yamllint disable-line rule:line-length
    - uses: pre-commit-ci/lite-action@5d6cc0eb514c891a40562a58a8e71576c5c7fb43 # v1.1.0
      if: ${{ !cancelled() }}
