---
name: Links
description: Checks the links in a repo work

inputs:
  github-token:
    description: GitHub token
    required: true

  lychee-args:
    description:
      Arguments to pass to lychee
      (https://github.com/lycheeverse/lychee#commandline-parameters)
    default: --no-progress --verbose './**/*.md' './**/*.html' './**/*.rst'

runs:
  using: composite
  steps:
    - name: Checkout source
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

    - name: Check links
      # yamllint disable-line rule:line-length
      uses: lycheeverse/lychee-action@a8c4c7cb88f0c7386610c35eb25108e448569cb0 # v2
      with:
        args: ${{ inputs.lychee-args }}
        failIfEmpty: false
        token: ${{ inputs.github-token }}
