---
name: Add Issues to Project
description: Add issues to the GitHub project board

inputs:
  app-id:
    description: Application ID
    required: true

  app-pem:
    description: Application private key
    required: true

  label:
    description: Label to filter issues by
    default: ""

  label-operator:
    description: Operator to filter issues by label
    default: OR

  project-url:
    description: URL of the project board to add issues to
    required: true

runs:
  using: composite
  steps:
    - name: Generate token
      id: generate-token
      # yamllint disable-line rule:line-length
      uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2
      with:
        app-id: ${{ inputs.app-id }}
        private-key: ${{ inputs.app-pem }}

    - name: Get project data
      # yamllint disable-line rule:line-length
      uses: actions/add-to-project@244f685bbc3b7adfa8466e08b698b5577571133e # v1.0.2
      with:
        github-token: ${{ steps.generate-token.outputs.token }}
        label-operator: ${{ inputs.label-operator }}
        label: ${{ inputs.label }}
        project-url: ${{ inputs.project-url }}
