---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: ./actions/links
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
